---
gunicorn:
  bind: "0.0.0.0:80"
  workers: 1
  threads: 20
  timeout: 3600
  keepalive: 3600
  daemon: false
  loglevel: "info"
predictors:
  predictor: snn_torch_predictor # snn_torch_predictor
  snn_torch_predictor:
    backend: TorchBackend   # SNNTorchBackend
    model_path: /model_zoo/latentsync_online_simple_auxilary/
    max_batch_size: 4
    warp_times: 1
    device: "cuda:0"
    fp16: False
    size: 768
    verbose: False
    perf_test_times: 1
    warm_times: 0
    save_debug_images: true 
    debug_output_path: "./output/"  # 相对于工作目录
    torch_compile: False
    
    # 业务配置文件路径
    config_file: "V1.0_latentsync_video_predictor.json"  # 业务配置文件路径
    # batching:
    #   type: dynamic
    #   # type: dummy
    #   max_batch_size: 8
    #   max_delay_time_ms: 100
    #   num_workers: 1
    #   preserve_slo: true
    #   irregular_batch_size: true
  snn_fast_predictor:
    backend: TensorRTBackend   # SNNTRTBackend
    model_path: ./
    batch_size: 1
    max_batch_size: 1
    fp16: True
    size: 768
    verbose: False
    perf_test_times: 1
    use_cuda_graph: False
