gunicorn:
  bind: 0.0.0.0:80
  daemon: false
  keepalive: 3600
  loglevel: info
  threads: 20
  timeout: 3600
  workers: 1
predictors:
  predictor: snn_torch_predictor
  snn_fast_predictor:
    backend: TensorRTBackend
    batch_size: 1
    fp16: true
    max_batch_size: 1
    model_path: ./
    perf_test_times: 1
    size: 768
    use_cuda_graph: false
    verbose: false
  snn_torch_predictor:
    backend: TorchBackend
    config_file: /home/fuping.chu/Avatar/ServerLatentSync/test/../models/V1.0_latentsync_video_predictor.json
    debug_output_path: ./output/
    debug_pipeline: false
    debug_video_merger: false
    device: cuda:0
    fp16: false
    inference_steps: 20
    max_batch_size: 4
    model_path: /model_zoo/latentsync_online_simple_auxilary/
    perf_test_times: 1
    save_debug_images: true
    seed: 1247
    size: 768
    target_fps: 25
    torch_compile: false
    verbose: false
    warm_times: 0
    warp_times: 1
